service: serverless-scorecard
app: serverless-scorecard
org: fernandomcsea

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::serverless-scorecard/*'
functions:
  hello:
    handler: handler.handler
    events:
      - schedule: rate(1 day)

plugins:
  - serverless-finch

custom:
  client:
    bucketName: serverless-scorecard
    distributionFolder: frontend
    errorDocument: index.html
